--- 
- name: "Vlan to access port verification on arista devices"
  connection: local
  gather_facts: false
  hosts: ARISTA01
  
  tasks: 
    - name: "Check Vlan membership on ARISTA01"
      eos_command: 
        commands: 
          - "show vlan brief"
      
      register: result
    - debug: 
        msg: "{{ result.stdout_lines }}"
