--- 
- name: "backup the cisco router config"
  connection: local
  gather_facts: false
  hosts: CSR02
  
  tasks: 
    - name: "show run only on CSR02"
      ios_command: 
        commands: 
          - "terminal length 0"
          - "show run"
          - "terminal length 24" 
      
      register: result
    - debug: 
        msg: "{{ result.stdout_lines }}"

    - name: save backup into a file
      copy: content="{{ result.stdout[1] }}" dest="/var/tmp/backup/{{ inventory_hostname }}.txt"
