--- 
- name: " access port config on Junos Switch"
  connection: local
  gather_facts: false
  hosts: JUNOS01
  
  tasks: 
    - name: delete interface config 
      junos_config:
        lines:
          - delete interfaces xe-0/0/4
          - delete interfaces xe-0/0/5
          - delete interfaces xe-0/0/6
          - delete interfaces xe-0/0/7
          - delete interfaces xe-0/0/8 
    - name: "l2 Interface config on junos devices"
      junos_config:
        lines:
          - set interfaces xe-0/0/4.0 family ethernet-switching interface-mode access vlan members vlan11
          - set interfaces xe-0/0/5.0 family ethernet-switching interface-mode access vlan members vlan12
          - set interfaces xe-0/0/6.0 family ethernet-switching interface-mode access vlan members vlan13
          - set interfaces xe-0/0/7.0 family ethernet-switching interface-mode access vlan members vlan14
          - set interfaces xe-0/0/8.0 family ethernet-switching interface-mode access vlan members vlan15
      
      register: result
    - debug: 
        msg: "{{ result }}"
