---
- name: Collect interface IP Details
  hosts: NXOS01
  gather_facts: false

  tasks:
    - name: collect the IP details
      raw: "show ip int brief | exclude unas"

      register: output
    -  debug: var=output.stdout_lines