--- 
- name: "L2 Interface creation on nexus Switch & pass vlan"
  connection: local
  gather_facts: false
  hosts: NXOS01
  
  tasks: 
    - name: L2 Access Port configuration
      nxos_l2_interface:
        name: ethernet1/2
        authorize: yes
        mode: access
        access_vlan: '11'

    - name: L2 Access ports configuration
      nxos_l2_interface:
         aggregate:
           - { name: ethernet1/3, access_vlan: '12' }
           - { name: ethernet1/4, access_vlan: '13' }
           - { name: ethernet1/5, access_vlan: '14' }
           - { name: ethernet1/6, access_vlan: '15' } 
           - { name: ethernet1/7, access_vlan: '16' }
           - { name: ethernet1/8, access_vlan: '17' }
           - { name: ethernet1/9, access_vlan: '18' }
           - { name: ethernet1/10, access_vlan: '19' }
           - { name: ethernet1/11, access_vlan: '20' }
         mode: access

      register: result
    - debug: 
        msg: "{{ result }}"
