---
- name: Add a NAT rule to the firewall
  hosts: PALO01
  connection: local
  gather_facts: no

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials
    include_vars: 'PA_vars.yml'

  - name: create inside object
    panos_address_object:
      provider: '{{ provider }}'
      name: 'INSIDE'
      value: '172.16.200.0/24'
      description: 'INSIDE object'


  - name: Create dynamic NAT rule on the firewall
    panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: 'PAT_Rule'
      source_zone: ['inside']
      destination_zone: 'outside'
      source_ip: ['INSIDE']
      destination_ip: ['any']
      to_interface: 'ethernet1/1'
      snat_type: 'dynamic-ip-and-port'
      snat_address_type: 'interface-address'
      snat_interface: 'ethernet1/1'
      snat_interface_address: ''
      state: 'present'
      commit: true
   
    register: result
 
  - debug:
      msg: '{{ result }}'

