---
- name: Add a NAT rule to the firewall
  hosts: PALO01
  connection: local
  gather_facts: no

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials
    include_vars: 'PA_vars.yml'

  - name: create object for web server
    panos_address_object:
      provider: '{{ provider }}'
      name: 'WEB-SERVER'
      value: '172.16.200.1'
      description: 'NXOS1 as a WEB SERVER'

  - name: Create a static NAT rule on the firewall
    panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: 'WEB_SERVER-Inbound'
      source_zone: ['outside']
      destination_zone: 'outside'
      source_ip: ['any']
      destination_ip: ['200.1.1.20']
      service: 'service-https'
      dnat_address: 'WEB-SERVER'
      state: 'present'

  - name: All https from outside to inside
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'WEB_SERVER-RULE'
      description: 'ALL-ONLY-HTTPS'
      source_zone: ['outside']
      source_ip: ['any']
      destination_zone: ['inside']
      destination_ip: ['200.1.1.20']
      application: ['any']
      service: 'service-https'
      action: 'allow'
    register: result

  - debug:
      msg: '{{result}}'

