---
- name: Add some address objects to the firewall
  hosts: PALO01
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Load Variables
    include_vars: PA_vars.yml
  
  - name: create objects
    panos_address_object:
      provider: "{{ provider }}"
      name: 'INSIDE-1'
      value: '1.1.1.1/32'
      description: 'INSIDE-1 object'

    register: result

  - debug:
      msg: '{{result}}'


