- name: Create Security policy
  hosts: PALO01
  connection: local
  gather_facts: false

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Grab auth creds
    include_vars: 'PA_vars.yml'
    no_log: 'yes'

  - name: All pass from inside to outside
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'INSIDE_TO_OUTSIDE'
      description: 'ALL-PASS'
      source_zone: ['inside']
      source_ip: ['any']
      destination_zone: ['outside']
      destination_ip: ['any']
      application: ['any']
      action: 'allow'
    register: result

  - debug:
      msg: '{{result}}'


