--- 
- name: " access port config on Junos Switch"
  connection: local
  gather_facts: false
  hosts: JUNOS01
  
  tasks: 
    - name: "l2 Interface config on junos devices"
      junos_l2_interface:
        name: xe-0/0/4
        mode: access
        access_vlan: vlan11
      register: result
    - debug: 
        msg: "{{ result }}"
